// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: saga_events.proto

package sagamodel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Arguments    *structpb.Struct `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Dependencies []string         `protobuf:"bytes,3,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
}

func (x *TaskDefinition) Reset() {
	*x = TaskDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saga_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDefinition) ProtoMessage() {}

func (x *TaskDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_saga_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDefinition.ProtoReflect.Descriptor instead.
func (*TaskDefinition) Descriptor() ([]byte, []int) {
	return file_saga_events_proto_rawDescGZIP(), []int{0}
}

func (x *TaskDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskDefinition) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *TaskDefinition) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type SagaBegun struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskDefinitions []*TaskDefinition `protobuf:"bytes,1,rep,name=task_definitions,json=taskDefinitions,proto3" json:"task_definitions,omitempty"`
}

func (x *SagaBegun) Reset() {
	*x = SagaBegun{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saga_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SagaBegun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SagaBegun) ProtoMessage() {}

func (x *SagaBegun) ProtoReflect() protoreflect.Message {
	mi := &file_saga_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SagaBegun.ProtoReflect.Descriptor instead.
func (*SagaBegun) Descriptor() ([]byte, []int) {
	return file_saga_events_proto_rawDescGZIP(), []int{1}
}

func (x *SagaBegun) GetTaskDefinitions() []*TaskDefinition {
	if x != nil {
		return x.TaskDefinitions
	}
	return nil
}

type SagaEnded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SagaEnded) Reset() {
	*x = SagaEnded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saga_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SagaEnded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SagaEnded) ProtoMessage() {}

func (x *SagaEnded) ProtoReflect() protoreflect.Message {
	mi := &file_saga_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SagaEnded.ProtoReflect.Descriptor instead.
func (*SagaEnded) Descriptor() ([]byte, []int) {
	return file_saga_events_proto_rawDescGZIP(), []int{2}
}

type TaskBegun struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TaskBegun) Reset() {
	*x = TaskBegun{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saga_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskBegun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskBegun) ProtoMessage() {}

func (x *TaskBegun) ProtoReflect() protoreflect.Message {
	mi := &file_saga_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskBegun.ProtoReflect.Descriptor instead.
func (*TaskBegun) Descriptor() ([]byte, []int) {
	return file_saga_events_proto_rawDescGZIP(), []int{3}
}

func (x *TaskBegun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TaskEnded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Result *structpb.Struct `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *TaskEnded) Reset() {
	*x = TaskEnded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saga_events_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskEnded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEnded) ProtoMessage() {}

func (x *TaskEnded) ProtoReflect() protoreflect.Message {
	mi := &file_saga_events_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEnded.ProtoReflect.Descriptor instead.
func (*TaskEnded) Descriptor() ([]byte, []int) {
	return file_saga_events_proto_rawDescGZIP(), []int{4}
}

func (x *TaskEnded) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskEnded) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

type TaskAborted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason *structpb.Struct `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *TaskAborted) Reset() {
	*x = TaskAborted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saga_events_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskAborted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAborted) ProtoMessage() {}

func (x *TaskAborted) ProtoReflect() protoreflect.Message {
	mi := &file_saga_events_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAborted.ProtoReflect.Descriptor instead.
func (*TaskAborted) Descriptor() ([]byte, []int) {
	return file_saga_events_proto_rawDescGZIP(), []int{5}
}

func (x *TaskAborted) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskAborted) GetReason() *structpb.Struct {
	if x != nil {
		return x.Reason
	}
	return nil
}

type CompensationBegun struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CompensationBegun) Reset() {
	*x = CompensationBegun{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saga_events_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompensationBegun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompensationBegun) ProtoMessage() {}

func (x *CompensationBegun) ProtoReflect() protoreflect.Message {
	mi := &file_saga_events_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompensationBegun.ProtoReflect.Descriptor instead.
func (*CompensationBegun) Descriptor() ([]byte, []int) {
	return file_saga_events_proto_rawDescGZIP(), []int{6}
}

func (x *CompensationBegun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CompensationEnded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CompensationEnded) Reset() {
	*x = CompensationEnded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saga_events_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompensationEnded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompensationEnded) ProtoMessage() {}

func (x *CompensationEnded) ProtoReflect() protoreflect.Message {
	mi := &file_saga_events_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompensationEnded.ProtoReflect.Descriptor instead.
func (*CompensationEnded) Descriptor() ([]byte, []int) {
	return file_saga_events_proto_rawDescGZIP(), []int{7}
}

func (x *CompensationEnded) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_saga_events_proto protoreflect.FileDescriptor

var file_saga_events_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x61, 0x67, 0x61, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x22, 0x72, 0x6e, 0x6f, 0x76, 0x61, 0x74, 0x6f, 0x72, 0x6f, 0x76, 0x2e,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x73, 0x61, 0x67, 0x61,
	0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x0e, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x22,
	0x0a, 0x0c, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69,
	0x65, 0x73, 0x22, 0x6a, 0x0a, 0x09, 0x53, 0x61, 0x67, 0x61, 0x42, 0x65, 0x67, 0x75, 0x6e, 0x12,
	0x5d, 0x0a, 0x10, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x72, 0x6e, 0x6f, 0x76,
	0x61, 0x74, 0x6f, 0x72, 0x6f, 0x76, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x2e, 0x73, 0x61, 0x67, 0x61, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x74,
	0x61, 0x73, 0x6b, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x0b,
	0x0a, 0x09, 0x53, 0x61, 0x67, 0x61, 0x45, 0x6e, 0x64, 0x65, 0x64, 0x22, 0x1b, 0x0a, 0x09, 0x54,
	0x61, 0x73, 0x6b, 0x42, 0x65, 0x67, 0x75, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4c, 0x0a, 0x09, 0x54, 0x61, 0x73, 0x6b,
	0x45, 0x6e, 0x64, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4e, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x62,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x23, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x6e,
	0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x65, 0x67, 0x75, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x23, 0x0a, 0x11, 0x43,
	0x6f, 0x6d, 0x70, 0x65, 0x6e, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x64, 0x65, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_saga_events_proto_rawDescOnce sync.Once
	file_saga_events_proto_rawDescData = file_saga_events_proto_rawDesc
)

func file_saga_events_proto_rawDescGZIP() []byte {
	file_saga_events_proto_rawDescOnce.Do(func() {
		file_saga_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_saga_events_proto_rawDescData)
	})
	return file_saga_events_proto_rawDescData
}

var file_saga_events_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_saga_events_proto_goTypes = []any{
	(*TaskDefinition)(nil),    // 0: rnovatorov.eventsource.saga_events.TaskDefinition
	(*SagaBegun)(nil),         // 1: rnovatorov.eventsource.saga_events.SagaBegun
	(*SagaEnded)(nil),         // 2: rnovatorov.eventsource.saga_events.SagaEnded
	(*TaskBegun)(nil),         // 3: rnovatorov.eventsource.saga_events.TaskBegun
	(*TaskEnded)(nil),         // 4: rnovatorov.eventsource.saga_events.TaskEnded
	(*TaskAborted)(nil),       // 5: rnovatorov.eventsource.saga_events.TaskAborted
	(*CompensationBegun)(nil), // 6: rnovatorov.eventsource.saga_events.CompensationBegun
	(*CompensationEnded)(nil), // 7: rnovatorov.eventsource.saga_events.CompensationEnded
	(*structpb.Struct)(nil),   // 8: google.protobuf.Struct
}
var file_saga_events_proto_depIdxs = []int32{
	8, // 0: rnovatorov.eventsource.saga_events.TaskDefinition.arguments:type_name -> google.protobuf.Struct
	0, // 1: rnovatorov.eventsource.saga_events.SagaBegun.task_definitions:type_name -> rnovatorov.eventsource.saga_events.TaskDefinition
	8, // 2: rnovatorov.eventsource.saga_events.TaskEnded.result:type_name -> google.protobuf.Struct
	8, // 3: rnovatorov.eventsource.saga_events.TaskAborted.reason:type_name -> google.protobuf.Struct
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_saga_events_proto_init() }
func file_saga_events_proto_init() {
	if File_saga_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_saga_events_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TaskDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_saga_events_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SagaBegun); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_saga_events_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SagaEnded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_saga_events_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TaskBegun); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_saga_events_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TaskEnded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_saga_events_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*TaskAborted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_saga_events_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*CompensationBegun); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_saga_events_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CompensationEnded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_saga_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_saga_events_proto_goTypes,
		DependencyIndexes: file_saga_events_proto_depIdxs,
		MessageInfos:      file_saga_events_proto_msgTypes,
	}.Build()
	File_saga_events_proto = out.File
	file_saga_events_proto_rawDesc = nil
	file_saga_events_proto_goTypes = nil
	file_saga_events_proto_depIdxs = nil
}
