// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: accounting_events.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountType int32

const (
	AccountType_UNKNOWN   AccountType = 0
	AccountType_CAPITAL   AccountType = 1
	AccountType_ASSET     AccountType = 2
	AccountType_LIABILITY AccountType = 3
	AccountType_INCOME    AccountType = 4
	AccountType_EXPENSE   AccountType = 5
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CAPITAL",
		2: "ASSET",
		3: "LIABILITY",
		4: "INCOME",
		5: "EXPENSE",
	}
	AccountType_value = map[string]int32{
		"UNKNOWN":   0,
		"CAPITAL":   1,
		"ASSET":     2,
		"LIABILITY": 3,
		"INCOME":    4,
		"EXPENSE":   5,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_accounting_events_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_accounting_events_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_accounting_events_proto_rawDescGZIP(), []int{0}
}

type BookCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *BookCreated) Reset() {
	*x = BookCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accounting_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookCreated) ProtoMessage() {}

func (x *BookCreated) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookCreated.ProtoReflect.Descriptor instead.
func (*BookCreated) Descriptor() ([]byte, []int) {
	return file_accounting_events_proto_rawDescGZIP(), []int{0}
}

func (x *BookCreated) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type BookClosed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BookClosed) Reset() {
	*x = BookClosed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accounting_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookClosed) ProtoMessage() {}

func (x *BookClosed) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookClosed.ProtoReflect.Descriptor instead.
func (*BookClosed) Descriptor() ([]byte, []int) {
	return file_accounting_events_proto_rawDescGZIP(), []int{1}
}

type BookAccountAdded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type AccountType `protobuf:"varint,2,opt,name=type,proto3,enum=rnovatorov.eventsource.examples.accounting_events.AccountType" json:"type,omitempty"`
}

func (x *BookAccountAdded) Reset() {
	*x = BookAccountAdded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accounting_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookAccountAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookAccountAdded) ProtoMessage() {}

func (x *BookAccountAdded) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookAccountAdded.ProtoReflect.Descriptor instead.
func (*BookAccountAdded) Descriptor() ([]byte, []int) {
	return file_accounting_events_proto_rawDescGZIP(), []int{2}
}

func (x *BookAccountAdded) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BookAccountAdded) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_UNKNOWN
}

type BookTransactionEntered struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp                 *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AccountDebited            string                 `protobuf:"bytes,2,opt,name=account_debited,json=accountDebited,proto3" json:"account_debited,omitempty"`
	AccountCredited           string                 `protobuf:"bytes,3,opt,name=account_credited,json=accountCredited,proto3" json:"account_credited,omitempty"`
	Amount                    uint64                 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	AccountDebitedNewBalance  uint64                 `protobuf:"varint,5,opt,name=account_debited_new_balance,json=accountDebitedNewBalance,proto3" json:"account_debited_new_balance,omitempty"`
	AccountCreditedNewBalance uint64                 `protobuf:"varint,6,opt,name=account_credited_new_balance,json=accountCreditedNewBalance,proto3" json:"account_credited_new_balance,omitempty"`
}

func (x *BookTransactionEntered) Reset() {
	*x = BookTransactionEntered{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accounting_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookTransactionEntered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookTransactionEntered) ProtoMessage() {}

func (x *BookTransactionEntered) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookTransactionEntered.ProtoReflect.Descriptor instead.
func (*BookTransactionEntered) Descriptor() ([]byte, []int) {
	return file_accounting_events_proto_rawDescGZIP(), []int{3}
}

func (x *BookTransactionEntered) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *BookTransactionEntered) GetAccountDebited() string {
	if x != nil {
		return x.AccountDebited
	}
	return ""
}

func (x *BookTransactionEntered) GetAccountCredited() string {
	if x != nil {
		return x.AccountCredited
	}
	return ""
}

func (x *BookTransactionEntered) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BookTransactionEntered) GetAccountDebitedNewBalance() uint64 {
	if x != nil {
		return x.AccountDebitedNewBalance
	}
	return 0
}

func (x *BookTransactionEntered) GetAccountCreditedNewBalance() uint64 {
	if x != nil {
		return x.AccountCreditedNewBalance
	}
	return 0
}

var File_accounting_events_proto protoreflect.FileDescriptor

var file_accounting_events_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x31, 0x72, 0x6e, 0x6f, 0x76, 0x61,
	0x74, 0x6f, 0x72, 0x6f, 0x76, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a,
	0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x0c,
	0x0a, 0x0a, 0x42, 0x6f, 0x6f, 0x6b, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x22, 0x7a, 0x0a, 0x10,
	0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x65, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x52, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x3e, 0x2e, 0x72, 0x6e, 0x6f, 0x76, 0x61, 0x74, 0x6f, 0x72, 0x6f, 0x76, 0x2e,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x5f,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xbe, 0x02, 0x0a, 0x16, 0x42, 0x6f, 0x6f,
	0x6b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x65,
	0x72, 0x65, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x27, 0x0a,
	0x0f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x64, 0x65, 0x62, 0x69, 0x74, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44,
	0x65, 0x62, 0x69, 0x74, 0x65, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x65,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3d, 0x0a, 0x1b, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x64, 0x65, 0x62, 0x69, 0x74, 0x65, 0x64, 0x5f, 0x6e, 0x65, 0x77,
	0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x18,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x62, 0x69, 0x74, 0x65, 0x64, 0x4e, 0x65,
	0x77, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x1c, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x65, 0x64, 0x5f, 0x6e, 0x65, 0x77,
	0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x19,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x65, 0x64, 0x4e,
	0x65, 0x77, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2a, 0x5a, 0x0a, 0x0b, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x41, 0x50, 0x49, 0x54, 0x41, 0x4c,
	0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x53, 0x53, 0x45, 0x54, 0x10, 0x02, 0x12, 0x0d, 0x0a,
	0x09, 0x4c, 0x49, 0x41, 0x42, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06,
	0x49, 0x4e, 0x43, 0x4f, 0x4d, 0x45, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x58, 0x50, 0x45,
	0x4e, 0x53, 0x45, 0x10, 0x05, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_accounting_events_proto_rawDescOnce sync.Once
	file_accounting_events_proto_rawDescData = file_accounting_events_proto_rawDesc
)

func file_accounting_events_proto_rawDescGZIP() []byte {
	file_accounting_events_proto_rawDescOnce.Do(func() {
		file_accounting_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_accounting_events_proto_rawDescData)
	})
	return file_accounting_events_proto_rawDescData
}

var file_accounting_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_accounting_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_accounting_events_proto_goTypes = []any{
	(AccountType)(0),               // 0: rnovatorov.eventsource.examples.accounting_events.AccountType
	(*BookCreated)(nil),            // 1: rnovatorov.eventsource.examples.accounting_events.BookCreated
	(*BookClosed)(nil),             // 2: rnovatorov.eventsource.examples.accounting_events.BookClosed
	(*BookAccountAdded)(nil),       // 3: rnovatorov.eventsource.examples.accounting_events.BookAccountAdded
	(*BookTransactionEntered)(nil), // 4: rnovatorov.eventsource.examples.accounting_events.BookTransactionEntered
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_accounting_events_proto_depIdxs = []int32{
	0, // 0: rnovatorov.eventsource.examples.accounting_events.BookAccountAdded.type:type_name -> rnovatorov.eventsource.examples.accounting_events.AccountType
	5, // 1: rnovatorov.eventsource.examples.accounting_events.BookTransactionEntered.timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_accounting_events_proto_init() }
func file_accounting_events_proto_init() {
	if File_accounting_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_accounting_events_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*BookCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accounting_events_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BookClosed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accounting_events_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*BookAccountAdded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accounting_events_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*BookTransactionEntered); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_accounting_events_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_accounting_events_proto_goTypes,
		DependencyIndexes: file_accounting_events_proto_depIdxs,
		EnumInfos:         file_accounting_events_proto_enumTypes,
		MessageInfos:      file_accounting_events_proto_msgTypes,
	}.Build()
	File_accounting_events_proto = out.File
	file_accounting_events_proto_rawDesc = nil
	file_accounting_events_proto_goTypes = nil
	file_accounting_events_proto_depIdxs = nil
}
